[plugin]
icon = "https://wu-clan.github.io/picx-images-hosting/logo/fba.svg"
summary = "AI"
version = "1.0.0"
description = "为系统提供 AI 赋能"
author = "wu-clan"
tags = ["agent", "ai"]
database = ["mysql", "postgresql"]

[app]
router = ["v1"]

[settings]
AI_HTTP_MAX_RETRIES = 5
